version: "3.1"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    image: node:alpine
    working_dir: /home/app
    restart: always
    volumes:
      - ./backend:/home/app
    command: ["npm", "run", "dev"]
  frontend:
    image: node:latest
    working_dir: /home/app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/app
    command: ["npm", "start"]