version: "3.1"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    image: node:alpine
    working_dir: /home/app
    restart: always
    volumes:
      - ./backend:/home/app
    command: ["npm", "run", "dev"]
    depends_on:
      - frontend
      - db
  frontend:
    image: node:latest
    working_dir: /home/app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/app
    command: ["npm", "start"]
  db:
    env_file:
      - .env
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD